# Generated by Django 3.2.19 on 2023-06-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
